import type { GameMetadata } from '../types/game'

export const GAMES_METADATA: GameMetadata[] = [
  {
    id: 'sdg-1-poverty-puzzle',
    title: 'Poverty Pathway',
    description: 'Navigate the right policies to help communities reach prosperity and reduce poverty.',
    sdgIds: ['1'],
    engine: 'resource',
    xpReward: 120,
    ecoCoinReward: 60,
    completedDescription: 'You helped shape a stronger safety net for people in need.',
    difficulty: 'medium',
    badgeId: 'sdg-1-champion',
    learningOutcome: 'Understand how resource allocation decisions affect poverty reduction and social equity.',
    completionRule: 'Choose the investment that maximizes long-term support while balancing community needs.',
    educationalFacts: [
      'Social protection systems help lift millions out of poverty when they are inclusive and targeted.',
      'Affordable housing, healthcare, and education are key drivers of sustainable poverty reduction.',
    ],
  },
  {
    id: 'sdg-2-food-chain',
    title: 'Food Chain Balance',
    description: 'Match farming, nutrition, and waste systems to keep the global food chain stable.',
    sdgIds: ['2'],
    engine: 'matching',
    xpReward: 100,
    ecoCoinReward: 50,
    completedDescription: 'You balanced sustainable agriculture and healthy food access.',
    difficulty: 'medium',
    badgeId: 'sdg-2-champion',
    learningOutcome: 'Learn how sustainable agriculture, nutrition, and waste management are linked across the food system.',
    completionRule: 'Match the right food system elements to achieve healthy diets and avoid waste.',
    educationalFacts: [
      'Sustainable food systems must provide nutritious food without degrading land or water resources.',
      'Reducing food loss and waste increases food security and lowers greenhouse gas emissions.',
    ],
  },
  {
    id: 'sdg-3-health-quest',
    title: 'Health Quest',
    description: 'Solve health system challenges by choosing the right care and prevention actions.',
    sdgIds: ['3'],
    engine: 'quiz',
    xpReward: 110,
    ecoCoinReward: 55,
    completedDescription: 'You improved access to healthcare and wellbeing for communities.',
    difficulty: 'easy',
    badgeId: 'sdg-3-champion',
    learningOutcome: 'Explore how public health, prevention, and care systems contribute to community wellbeing.',
    completionRule: 'Answer health decisions that strengthen access, prevention, and equity.',
    educationalFacts: [
      'Investing in preventive healthcare reduces illnesses and supports long-term sustainable development.',
      'Health services are essential for reducing vulnerabilities to environmental and social shocks.',
    ],
  },
  {
    id: 'sdg-4-learning-lab',
    title: 'Learning Lab',
    description: 'Design a learning path that connects learners to resources, teachers, and schools.',
    sdgIds: ['4'],
    engine: 'puzzle',
    xpReward: 120,
    ecoCoinReward: 60,
    completedDescription: 'You created a more inclusive and quality learning environment.',
    difficulty: 'medium',
    badgeId: 'sdg-4-champion',
    learningOutcome: 'Recognize the building blocks of quality education and inclusive learning systems.',
    completionRule: 'Complete each step of the learning ecosystem puzzle to unlock the full pathway.',
    educationalFacts: [
      'Quality education is vital for empowering learners to address sustainability and climate challenges.',
      'Teacher training and inclusive access help make learning systems more equitable and resilient.',
    ],
  },
  {
    id: 'sdg-5-equality-match',
    title: 'Equality Match',
    description: 'Pair role models, policies, and rights to support gender equality across sectors.',
    sdgIds: ['5'],
    engine: 'matching',
    xpReward: 110,
    ecoCoinReward: 55,
    completedDescription: 'You advanced gender equality by connecting people and opportunities.',
    difficulty: 'easy',
    badgeId: 'sdg-5-champion',
    learningOutcome: 'Learn how gender equality and social inclusion support sustainable outcomes for communities.',
    completionRule: 'Match equality resources, leadership, and legal protections correctly.',
    educationalFacts: [
      'Gender equality increases resilience by ensuring all voices are included in environmental planning.',
      'Equal access to education and work empowers women and girls to shape sustainable futures.',
    ],
  },
  {
    id: 'sdg-6-water-sort',
    title: 'Water Sort',
    description: 'Sort water sources, treatments, and uses to protect safe water systems.',
    sdgIds: ['6'],
    engine: 'drag-drop',
    xpReward: 100,
    ecoCoinReward: 50,
    completedDescription: 'You safeguarded clean water access and sanitation services.',
    difficulty: 'easy',
    badgeId: 'sdg-6-champion',
    learningOutcome: 'Understand clean water solutions and the importance of wastewater treatment for healthy ecosystems.',
    completionRule: 'Select safe water actions and avoid pollution risks to complete the challenge.',
    educationalFacts: [
      'Safe water and sanitation are essential for protecting health and preventing waterborne disease.',
      'Healthy freshwater systems support both people and natural habitats.',
    ],
  },
  {
    id: 'sdg-7-energy-grid',
    title: 'Energy Grid',
    description: 'Manage renewable and efficient energy choices for a reliable power system.',
    sdgIds: ['7'],
    engine: 'simulation',
    xpReward: 120,
    ecoCoinReward: 60,
    completedDescription: 'You helped build a cleaner and more affordable energy network.',
    difficulty: 'medium',
    badgeId: 'sdg-7-champion',
    learningOutcome: 'Explore renewable energy and efficiency choices that support modern sustainable power systems.',
    completionRule: 'Choose a balanced energy mix that improves reliability and lowers emissions.',
    educationalFacts: [
      'Renewable energy sources like solar and wind reduce pollution and expand access to clean power.',
      'Energy efficiency helps communities use less power while meeting essential needs.',
    ],
  },
  {
    id: 'sdg-8-growth-journey',
    title: 'Growth Journey',
    description: 'Help businesses and workers reach decent jobs while building economic growth.',
    sdgIds: ['8'],
    engine: 'strategy',
    xpReward: 110,
    ecoCoinReward: 55,
    completedDescription: 'You guided sustainable economic growth and fair work.',
    difficulty: 'medium',
    badgeId: 'sdg-8-champion',
    learningOutcome: 'Discover how decent work and sustainable business models contribute to inclusive prosperity.',
    completionRule: 'Select the economic choices that support fair jobs and long-term growth.',
    educationalFacts: [
      'Decent work improves wellbeing and anchors communities in sustainable development.',
      'Economic growth must be inclusive and resource-efficient to be sustainable.',
    ],
  },
  {
    id: 'sdg-9-innovation-network',
    title: 'Innovation Network',
    description: 'Connect industry, infrastructure, and innovation to create sustainable progress.',
    sdgIds: ['9'],
    engine: 'strategy',
    xpReward: 130,
    ecoCoinReward: 65,
    completedDescription: 'You built resilient infrastructure for a more innovative future.',
    difficulty: 'hard',
    badgeId: 'sdg-9-champion',
    learningOutcome: 'Understand how sustainable infrastructure and innovation create inclusive economic opportunities.',
    completionRule: 'Build a system of investments that balances innovation, resilience, and sustainability.',
    educationalFacts: [
      'Sustainable infrastructure supports access to education, healthcare, and clean energy.',
      'Innovation can help countries adapt to climate change and grow more equitably.',
    ],
  },
  {
    id: 'sdg-10-justice-climb',
    title: 'Justice Climb',
    description: 'Align policy, access, and support systems that reduce inequality at scale.',
    sdgIds: ['10'],
    engine: 'quiz',
    xpReward: 105,
    ecoCoinReward: 50,
    completedDescription: 'You made society fairer by narrowing inequality gaps.',
    difficulty: 'easy',
    badgeId: 'sdg-10-champion',
    learningOutcome: 'Explore the role of inclusive policy and social support in reducing inequality.',
    completionRule: 'Choose the fairness-focused solutions that help equalize access and opportunity.',
    educationalFacts: [
      'Reducing inequalities creates stronger, more resilient societies and improves environmental outcomes.',
      'Equitable access to services helps ensure no one is left behind in the sustainability transition.',
    ],
  },
  {
    id: 'sdg-11-city-planner',
    title: 'City Planner',
    description: 'Place transit, housing, and green spaces to create a safer sustainable city.',
    sdgIds: ['11'],
    engine: 'simulation',
    xpReward: 130,
    ecoCoinReward: 65,
    completedDescription: 'You designed a more resilient and inclusive urban future.',
    difficulty: 'hard',
    badgeId: 'sdg-11-champion',
    learningOutcome: 'Learn how urban planning can improve equity, resilience, and environmental performance.',
    completionRule: 'Choose city investments that boost safety, mobility, and shared green infrastructure.',
    educationalFacts: [
      'Sustainable cities prioritize walking, cycling, public transit, and open green spaces.',
      'Equitable urban planning ensures all residents can access services, jobs, and safe housing.',
    ],
  },
  {
    id: 'sdg-12-waste-wisdom',
    title: 'Waste Wisdom',
    description: 'Sort materials and choose circular choices to reduce waste and pollution.',
    sdgIds: ['12'],
    engine: 'sorting',
    xpReward: 100,
    ecoCoinReward: 50,
    completedDescription: 'You improved responsible consumption and waste systems.',
    difficulty: 'easy',
    badgeId: 'sdg-12-champion',
    learningOutcome: 'Understand responsible consumption, recycling, and circular systems for lower environmental impact.',
    completionRule: 'Choose the circular options that minimize waste and maximize reuse.',
    educationalFacts: [
      'The circular economy helps reduce pollution and conserve finite resources.',
      'Proper sorting and recycling keep materials in use longer and cut waste disposal costs.',
    ],
  },
  {
    id: 'sdg-13-climate-crisis',
    title: 'Climate Crisis',
    description: 'Make fast decisions to lower emissions and prepare communities for climate risks.',
    sdgIds: ['13'],
    engine: 'decision',
    xpReward: 130,
    ecoCoinReward: 65,
    completedDescription: 'You helped communities adapt to climate impacts and reduce climate risk.',
    difficulty: 'hard',
    badgeId: 'sdg-13-champion',
    learningOutcome: 'See how climate actions and adaptation planning strengthen community resilience.',
    completionRule: 'Select the climate choices that reduce emissions and protect vulnerable populations.',
    educationalFacts: [
      'Climate resilience requires both cutting emissions and preparing communities for extreme weather.',
      'Adaptation planning saves lives and reduces long-term recovery costs after climate disasters.',
    ],
  },
  {
    id: 'sdg-14-ocean-keeper',
    title: 'Ocean Keeper',
    description: 'Match marine protections, fisheries, and pollution controls in a fragile ocean system.',
    sdgIds: ['14'],
    engine: 'matching',
    xpReward: 110,
    ecoCoinReward: 55,
    completedDescription: 'You protected ocean life and sustainable sea resources.',
    difficulty: 'medium',
    badgeId: 'sdg-14-champion',
    learningOutcome: 'Understand how marine conservation and sustainable fisheries keep oceans healthy.',
    completionRule: 'Pair protections, fishing practices, and pollution controls for a healthier ocean.',
    educationalFacts: [
      'Healthy oceans regulate climate, support biodiversity, and provide food for billions of people.',
      'Marine pollution and overfishing threaten coastal communities and ocean ecosystems.',
    ],
  },
  {
    id: 'sdg-15-forest-guard',
    title: 'Forest Guard',
    description: 'Balance biodiversity, land use, and conservation to restore healthy ecosystems.',
    sdgIds: ['15'],
    engine: 'simulation',
    xpReward: 120,
    ecoCoinReward: 60,
    completedDescription: 'You restored habitats and strengthened ecosystem health.',
    difficulty: 'medium',
    badgeId: 'sdg-15-champion',
    learningOutcome: 'Explore how forest restoration and sustainable land use protect biodiversity and people.',
    completionRule: 'Select conservation and community actions that support forest health.',
    educationalFacts: [
      'Forests support biodiversity, clean air, and climate stability around the world.',
      'Sustainable land use prevents degradation and protects critical wildlife habitats.',
    ],
  },
  {
    id: 'sdg-16-peace-builder',
    title: 'Peace Builder',
    description: 'Resolve conflicts with community support, justice, and dialogue for lasting peace.',
    sdgIds: ['16'],
    engine: 'quiz',
    xpReward: 120,
    ecoCoinReward: 60,
    completedDescription: 'You fostered safe, inclusive and accountable societies.',
    difficulty: 'medium',
    badgeId: 'sdg-16-champion',
    learningOutcome: 'Learn how justice, strong institutions, and cooperation contribute to sustainable peace.',
    completionRule: 'Choose solutions that build accountability, inclusion, and conflict resolution.',
    educationalFacts: [
      'Strong institutions and transparent governance support long-term sustainability and justice.',
      'Peaceful societies are better able to manage natural resources fairly and sustainably.',
    ],
  },
  {
    id: 'sdg-17-global-link',
    title: 'Global Link',
    description: 'Coordinate partnerships, funding, and shared goals to solve world challenges together.',
    sdgIds: ['17'],
    engine: 'strategy',
    xpReward: 130,
    ecoCoinReward: 65,
    completedDescription: 'You strengthened global collaboration for sustainable development.',
    difficulty: 'hard',
    badgeId: 'sdg-17-champion',
    learningOutcome: 'Understand how partnerships, finance, and shared goals accelerate sustainable development.',
    completionRule: 'Assemble the right collaborations and resources to support all SDGs together.',
    educationalFacts: [
      'Global partnerships help share knowledge, funding, and technology across countries.',
      'Coordinated action across sectors is essential to achieve the Sustainable Development Goals.',
    ],
  },
]

export function getGameById(gameId: string): GameMetadata | undefined {
  return GAMES_METADATA.find((game) => game.id === gameId)
}
